### ISSUE TITLE
Invalid Literal value for 200 OK status code

### ISSUE THREAD

**Issue by francis-clairicia** [sbdchd/djangorestframework-types#15]
rel: https://github.com/sbdchd/djangorestframework-types/blob/d5aa9a86331b02bcc9bfc7a5d0baaa0f439f6c14/typings/rest_framework/status.pyi#L11

**Comment by sbdchd** [comment]
Whoops!

**Comment by knyghty** [comment]
Can you close this issue? Looks like it was fixed.

**Comment by francis-clairicia** [comment]
You're right. Thanks
